sudo: required
services:
 - docker

before_install:
 - docker build -t dipankars/docker-react -f Dockerfile.dev .


script:
 - docker run dipankars/docker-react npm run test -- --coverage 

deploy:
 provider: elasticbneanstalk
 region: "us-east-2"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-east-2-966237154433"
 bucket_path: "docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secure_access_key:
  secure: $AWS_SECRET_KEY
